services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    image: eventhub-jenkins:latest
    container_name: eventhub_jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
